data:
  data_dir: "data/"
  data_name: "rest_tremor_constancy.npz"
  data_loader: "new_loader"

feature:
  feature_extractor: "minirocket"

split:
  split_type: "train_val_test_split"

train:
  model_name: "tremor_constancy_minirocket_rrc"
  model_type: "rrc"
  model_dir: "model"
  report_dir: "reports"