raw_data_cfg:
  # 数据路径
  raw_data_dir: "data/raw/"

  # 配合 Noraxon 导出数据格式
  skiprows: 3         # 跳过第 1，2 行
  skipcols: [1, 2]    # 跳过第 2，3 列
  header: 3           # 第 3 行作为表头
  dtype: {2: 'str'}   # 第 3 列的数据类型为字符串

  # 各传感模态对应的数据所处列数（除去 2，3 两列）
  data_modal:
    # 上肢未配备 IMU 的测试数据
    old:
      emg: [1, 2, 3, 4, 5, 15, 25, 35]
      acc: [6, 7, 8, 16, 17, 18, 26, 27, 28, 36, 37, 38]
      gyro: [9, 10, 11, 19, 20, 21, 29, 30, 31, 39, 40, 41]
      mag: [12, 13, 14, 22, 23, 24, 32, 33, 34, 42, 43, 44]
    # 上肢配备 IMU 的测试数据
    new:
      emg: [1, 11, 12, 22, 23, 33, 34, 44]
      acc: [2, 3, 4, 13, 14, 15, 24, 25, 26, 35, 36, 37]
      gyro: [5, 6, 7, 16, 17, 18, 27, 28, 29, 38, 39, 40]
      mag: [8, 9, 10, 19, 20, 21, 30, 31, 32, 41, 42, 43]

processed_data_dir: "data/processed/"
# TODO: add more data configs
batch_size: 32
shuffle: True
